- name: Ansible Vault Reader role
  hosts: localhost
  gather_facts: no
  roles:
    - role: ansible_vault_reader

- name: Configure Proxmox
  hosts: ansible_controller_1
  gather_facts: yes
  vars:
    vault_vars: "{{ hostvars['VAULT_HOST'].vault_secrets.secret }}"
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - sudo
        - git
  
    - name: Install Python packages
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - ansible
        - pyvmomi
        - proxmoxer
        - requests
        - jmespath