all:
  children:
    ansible_controllers:
      hosts:
        Ansible-Controller-01:
          ansible_host: 192.168.0.195
    gitlab:
      hosts:
        GitLab-01:
          ansible_host: 192.168.0.117
    proxmox_servers:
      hosts:
        Proxmox-01:
          ansible_host: 192.168.0.128
    palserver:
      hosts:
        PalServer-01:
          ansible_host: 192.168.0.138
    proxmox:
      children:
        proxmox_servers:
        ansible_controllers:
        palserver:
        gitlab:
