---

- name: Include variables from ansible vault
  hosts: localhost
  gather_facts: no
  roles:
    - role: ansible_vault_reader

- name: Include variables from ansible vault
  hosts: localhost
  gather_facts: no
  vars:
    vault_vars: "{{ hostvars['VAULT_HOST'].vault_secrets.secret }}"
    base_name: "Test-"
    start_index: 1
    max_attempts: 100

  tasks:
    - name: Obtain Authentication Token
      uri:
        url: "https://{{ proxmox_ip }}/api2/json/access/ticket"
        method: POST
        body_format: form-urlencoded
        body:
          username: "{{ api_user }}"
          password: "{{ api_password }}"
        validate_certs: no
        force_basic_auth: yes
      register: login_response

    - name: Set Authentication Token and CSRF Token as Facts
      set_fact:
        auth_cookie: "{{ login_response.json.data.ticket }}"
        csrf_token: "{{ login_response.json.data.CSRFPreventionToken }}"

    - name: VM Name Block
      block:
        - name: Prompt for VM name or press Enter to auto-generate
          pause:
            prompt: "Enter the name of the VM to create or press Enter to auto-generate: "
          register: manual_vm_name_input

        - name: Set VM name from input if provided
          set_fact:
            vm_name: "{{ manual_vm_name_input.user_input | default('') }}"
          when: manual_vm_name_input.user_input is defined and manual_vm_name_input.user_input | length > 0

      when: vm_name is not defined or vm_name | length == 0

    - name: List VMs on Proxmox node using Token
      uri:
        url: "https://{{ proxmox_ip }}/api2/json/nodes/{{ node | default('proxmox') }}/qemu"
        method: GET
        return_content: yes
        headers:
          Cookie: "PVEAuthCookie={{ auth_cookie }}"
        validate_certs: no
      register: vm_list_response

    - name: Check if VM name exists
      set_fact:
        vm_name_exists: "{{ vm_list_response.json.data | json_query('[?name==`' + vm_name + '`]') | length > 0 }}"
      when: vm_list_response.status == 200

    - name: Use the available VM name for further operations
      debug:
        msg: "Using VM name: {{ vm_name }}"

    - name: Clone VM from Template
      community.general.proxmox_kvm:
        api_user: "{{ api_user | default('root@pam') }}"
        api_password: "{{ vault_vars.proxmox_password }}"
        api_host: "{{ proxmox_ip }}"
        validate_certs: no
        node: "{{ node | default('proxmox')}}"
        vmid: "{{ vmid | default('105') }}"
        name: "{{ vm_name }}"
        clone: "{{ vm_template | default('rocky_linux_template') }}"
        target: "{{ node | default('proxmox')}}"  
        full: "{{ vm_full | default('yes') }}"
        storage: "{{ vm_storage | default('local-lvm') }}"
        format: "{{ vm_format | default('raw') }}"
        timeout: "600"
      register: clone_result

    - name: Fail if VM with name already exists
      fail:
        msg: "VM with name {{ vm_name }} already exists"
      when: "'VM with name' in clone_result.msg"

    - name: Conditionally create VM from ISO if specified
      community.general.proxmox_kvm:
        api_user: "{{ api_user | default('root@pam') }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        validate_certs: no
        node: "{{ node }}"
        vmid: "{{ vmid | default(omit) }}"
        name: "{{ vm_name }}"
        memory: "{{ vm_memory | default(2048) }}"
        cores: "{{ vm_cores | default(2) }}"
        net:
          net0: "virtio,bridge={{ vm_net_bridge | default('vmbr0') }}"
        virtio:
          virtio0: "local={{ vm_disk_size | default('10G') }},format=qcow2"
        iso: "{{ vm_iso }}"
      when: vm_iso is defined and vm_iso | length > 0
