all:
  children:
    ansible_controllers:
      hosts:
        ansible_controller_1:
          ansible_host: 192.168.0.195
    gitlab_servers:
      hosts:
        gitlab_server_1:
          ansible_host: 192.168.0.117
    proxmox_servers:
      hosts:
        proxmox_server_1:
          ansible_host: 192.168.0.128
    game_servers:
      hosts:
        palserver_1:
          ansible_host: 192.168.0.138
    proxmox:
      children:
        proxmox_servers:
        ansible_controllers:
        game_servers:
        gitlab_servers: