---

- name: Run vault_reader role
  hosts: localhost
  gather_facts: no
  roles:
    - role: ansible_vault_reader

- name: Create new sudo user on all hosts
  hosts: all
  gather_facts: no
  vars:
    vault_vars: "{{ hostvars['VAULT_HOST'].vault_secrets.secret }}"
  tasks:

    - name: Create new user and set password
      become: yes
      user:
        name: bobbyhiddn
        password: "{{ vault_vars.bobbyhiddn_password | password_hash('sha512') }}"
        update_password: on_create

    - name: Allow new user to have sudo access
      become: yes
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^bobbyhiddn'
        line: 'bobbyhiddn ALL=(ALL:ALL) ALL'
        validate: 'visudo -cf %s'

    - name: Ensure home directory ownership is correct
      become: yes
      file:
        path: /home/bobbyhiddn
        state: directory
        owner: bobbyhiddn
        group: bobbyhiddn
        recurse: yes

    - name: Update password for bobbyhiddn
      become: yes
      user:
        name: bobbyhiddn
        password: "{{ vault_vars.bobbyhiddn_password | password_hash('sha512') }}"
        update_password: always
